# Generated by Django 6.0.1 on 2026-04-09 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_saved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saved',
            options={'verbose_name': 'Saved', 'verbose_name_plural': 'Saved'},
        ),
        migrations.AlterUniqueTogether(
            name='saved',
            unique_together={('post', 'user')},
        ),
    ]
