# Generated by Django 6.0.1 on 2026-05-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_comment_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='comment',
            name='core_commen_post_id_7e3d35_idx',
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='core_commen_user_id_315d2e_idx',
        ),
        migrations.RemoveIndex(
            model_name='following',
            name='core_follow_followe_9c01e0_idx',
        ),
        migrations.RemoveIndex(
            model_name='following',
            name='core_follow_followi_350832_idx',
        ),
        migrations.RemoveIndex(
            model_name='like',
            name='core_like_user_id_11e37b_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='core_post_user_id_5973f4_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='core_post_visibil_48b154_idx',
        ),
        migrations.RemoveIndex(
            model_name='saved',
            name='core_saved_user_id_b759cd_idx',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10),
        ),
    ]
