# Generated by Django 6.0.1 on 2026-05-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_comment_core_commen_post_id_7e3d35_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], db_index=True, default='public', max_length=10),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', '-created_at'], name='core_commen_post_id_7e3d35_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['user', '-created_at'], name='core_commen_user_id_315d2e_idx'),
        ),
        migrations.AddIndex(
            model_name='following',
            index=models.Index(fields=['follower', '-created_at'], name='core_follow_followe_9c01e0_idx'),
        ),
        migrations.AddIndex(
            model_name='following',
            index=models.Index(fields=['following', '-created_at'], name='core_follow_followi_350832_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['user', '-created_at'], name='core_like_user_id_11e37b_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['user', '-created_at'], name='core_post_user_id_5973f4_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['visibility', '-created_at'], name='core_post_visibil_48b154_idx'),
        ),
        migrations.AddIndex(
            model_name='saved',
            index=models.Index(fields=['user', '-created_at'], name='core_saved_user_id_b759cd_idx'),
        ),
    ]
